[project]
name = "envsim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT AND (Apache-2.0 OR BSD-2-Clause)"
dependencies = [
    "numpy>=2.2.4",
    "perlin-noise>=1.13",
    "pygame>=2.6.1",
]
